#!/bin/bash
if [ $# -lt 2 ]; then 
  echo 'could take more params like :' $0 computerNumber coresByAVM
 fi

if [ -e ../jars/DataCenter.jar ]; then
  java -ea -cp '../jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     fr.upmc.examples.admissioncontroller.DistribuedApplicationController controller config.xml $1
else
  echo 'The project must be exported into a jar named DataCenter.jar in folder ../jars'
fi


